/* empty css                      */import{S as v,i as d,a as B}from"./assets/vendor-DTWVMNYS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E=document.getElementById("form"),u=document.getElementById("search"),m=document.getElementById("loader-center"),p=document.getElementById("gallery"),w=document.getElementById("load-more"),c=document.getElementById("load-more-container"),f=document.getElementById("loader-below-button"),I=new v(".gallery a",{captionsData:"alt",captionDelay:250}),P="51314790-8eb7b58c862d15e75f23e4ac3";let l="",a=1;const h=40;d.settings({position:"topRight"});async function g(n,t=1){const o="https://pixabay.com/api/",s={key:P,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:h};try{return(await B.get(o,{params:s})).data}catch(e){return console.error("Error fething images:",e),{hits:[],totalHits:0}}}E.addEventListener("submit",async n=>{n.preventDefault();const t=u.value.trim();if(u.value="",t==="")return;l=t,a=1,p.innerHTML="",m.classList.remove("hidden"),c.classList.add("hidden");const{hits:o,totalHits:s}=await g(l,a);if(m.classList.add("hidden"),o.length===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(o),s>h&&c.classList.remove("hidden")});w.addEventListener("click",async()=>{a+=1,f.classList.remove("hidden");const{hits:n}=await g(l,a);if(f.classList.add("hidden"),n.length>0){y(n);const t=document.querySelector(".gallery a");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}else c.classList.add("hidden"),d.info({message:"We're sorry, but you've reached the end of search results"})});function y(n){const t=n.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:i,comments:b,downloads:L})=>`
      <a href="${s}" class="photo-card">
        <img src="${o}" alt="${e}"/>
        <div class="info">
          <p><b>Likes</b><br> ${r}</p>
          <p><b>Views</b><br> ${i}</p>
          <p><b>Comments</b><br> ${b}</p>
          <p><b>Downloads</b><br> ${L}</p>
        </div>
      </a>
    `).join("");p.insertAdjacentHTML("beforeend",t),I.refresh()}
//# sourceMappingURL=index.js.map
